### ISSUE TITLE
Room bookings

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/ecr-day#1]
```[tasklist]
### Tasks
- [x] book Enigma for the whole day
- [x] book additional rooms for ReproHack
- [x] book table for lunch
- [x] book table for breakfast?
- [x] talk to IT about having screens in Enigma for the discussions
- [x] register attendees with reception
```

**Comment by BatoolMM** [comment]
Hi @eirini-zormpa, I am happy to speak with facilities around the booking table for breakfast - also I can contact IT about the screens. Is this any different than the screens we already have on Enigma?

**Comment by BatoolMM** [comment]
@eirini-zormpa would you mind if you can include me on the calendar invite for the room booking, so I have it on my calendar with the rooms?

**Comment by BatoolMM** [comment]
Thank you for including me in the invite :) - 

Just flagging again the conversation about the room capacity for Engima (45 only). If you do need a bigger toom, I looked into the cost of rooms in the British library (we should be able to afford them according to the budget), just in case you were wondering about them.

VENUE ACCESS
Full day hire 08.30 to 17.00 or
half day hire: 08.30-12.30 o/ 13.00-17.00
Evening Hire: 18.00-22.00
 
- **Eliot** : Max capacity 60x theatre/28 x boardroom
Full day hire: £1505.00
Half day Hire/Evening hire: £1160.00(Wednesday evenings only)
      
<img width="686" alt="Screenshot 2023-08-22 at 15 54 53" src="https://github.com/aim-rsf/ecr-day/assets/53487593/6f057f4e-02a2-4dfd-8cf0-95d48a37bc84">

- **Bronte** : Max capacity 60x theatre/24 x boardroom – Bronte room can be spilt into 2 separate rooms: capacity 30/25 theatre style
Full day hire:  £1505.00
Half day Hire/Evening hire: £1160.00(Wednesday evenings only)

<img width="355" alt="Screenshot 2023-08-22 at 15 55 11" src="https://github.com/aim-rsf/ecr-day/assets/53487593/af8608fd-6640-442d-973f-d27ec99490a4">

**Comment by eirini-zormpa** [comment]
@all-contributors please add @eirini-zormpa for ideas

**Comment by eirini-zormpa** [comment]
@all-contributors please add @BatoolMM for ideas

**Comment by eirini-zormpa** [comment]
@all-contributors please add @eirini-zormpa for eventOrganizing. please add @BatoolMM for eventOrganizing. please add @SydneyAmbrose for eventOrganizing

**Comment by BatoolMM** [comment]
Thank you again @eirini-zormpa ❤️
