### ISSUE TITLE
Master checklist for in-person ECR events

### ISSUE THREAD

**Issue by BatoolMM** [aim-rsf/ecr-day#10]
# Master checklist for in-person ECR events

- [ ] Budget allocated and approved
- [ ] Event plan outlined and discussed with ops team
- [ ] Registration opened
- [ ] Registration closed
- [ ] Accessibility needs collected and investigated
- [ ] Accessibility needs recorded with details
- [ ] Hotel rooms booked
- [ ] Hotel reservations paid
- [ ] Catering booked
- [ ] Dinner venue booked
- [ ] Dinner expenses paid
- [ ] All participants contacted and hotel bookings confirmed
- [ ] Closed Slack Channel created
- [ ] Project Managers (RC PMs) contacted regarding reimbursement
- [ ] DocuSign for  reimbursement is sent
- [ ] Papers for ReproHack selected
- [ ] Event program finalised and shared with participants
- [ ] Travel arrangements from dinner to hotel is made for folks that has mobility health issue
- [ ] Event materials (name badges) printed and ready
- [ ] Backup plan for technical issues in place 
- [ ] Emergency contact information shared with participant 
- [ ] Social media promotion plan in action (Twitter, LinkedIn) 
- [ ] Booklet prints with COMPUTE new plain English summary
- [ ] Evaluation forms created for feedback collection
- [ ] Event day logistics double-checked (timetables, etc.)
- [ ] Technical support team ready to handle any AV or IT issues
- [ ] Post-event survey or feedback form drafted for participants
- [ ] Thank-you notes prepared for speakers/ECR
- [ ] Event photos or recordings planned and arranged
- [ ] Event debrief meeting scheduled to review successes and areas for improvement

**Comment by eirini-zormpa** [comment]
this is comprehensive, thank you so much Batool!

**Comment by BatoolMM** [comment]
Here is some slides to warp up the ECR day!
https://docs.google.com/presentation/d/1IXzStjDRSEy6-w3hj5HCHnJauHxAuyq43COjUllat-I/edit#slide=id.g2a2699d3993_0_107
