### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/ecr-day#2]
```[tasklist]
### Tasks
- [x] decide what to order (timings, need coffee?)
- [x] find out how many people to order catering for
- [x] make a list of dietary requirements
- [x] submit request form
```

**Comment by eirini-zormpa** [comment]
[Catering instructions on Mathison](https://mathison.turing.ac.uk/page/2494?SearchId=294604)

**Comment by BatoolMM** [comment]
I asked a few programmes about their experience with British Librray catering - not very recommended. They have recommended instead "[The Garden catering](https://thegardencatering.com/)", they are in Turing System. They also seem to be cheaper and better, with more options!

**Comment by eirini-zormpa** [comment]
@all-contributors please add @SydneyAmbrose for eventOrganizing

**Comment by BatoolMM** [comment]
Thank you again @eirini-zormpa ❤️
