### ISSUE TITLE
ReproHack

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/ecr-day#3]
The afternoon of the event will be a [ReproHack](https://www.reprohack.org/).

```[tasklist]
### to-do
- [x] find papers from ReproHack website
- [x] ask for paper suggestions from attendees
- [x] decide whether to invite Turing ECRs
- [x] figure out timings (how long to spend on ReproHack vs report
- [x] decide on platform - should new papers be registered on the website?
- [x] how will people get into teams/choose papers?
- [x] invite additional facilitators
- [x] write up learning outcomes and motivation
```

**Comment by eirini-zormpa** [comment]
normally people would decide during the event, but I agree that it would take time we don't have. I don't think we can have people pick papers during the registration though. the ones from the reprohack website aren't super relevant, so I'd like to source more. we could contact people a few weeks before the event with options, but we may not get responses from everyone

**Comment by BatoolMM** [comment]
Thank you again @eirini-zormpa ❤️
