### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/ecr-day#4]
```[tasklist]
### Tasks
- [x] create poster
- [x] create an information page (GitHub)
- [x] write email to attendees
- [x] create registration form
```

**Comment by BatoolMM** [comment]
@eirini-zormpa do you have a timeline for when you want to open and close registration so I can help with chasing and collecting the registration?

**Comment by eirini-zormpa** [comment]
excellent question! I think we should open registrations as soon as possible, but we need to know if we can pay for things in advance before we do... any updates on that?

**Comment by BatoolMM** [comment]
Yes, I found a way of securing the hotel booking without reimbursement but I just want to double-check with Georgette as she will be the one who approves it. I started a new issue #6 so I can track this information there.

**Comment by eirini-zormpa** [comment]
LEGEND!

**Comment by BatoolMM** [comment]
I confirmed the new way of paying for the hotels directly. The process is documented [here](https://hackmd.io/cmI-rXf-QteHTvAWsdH87w). I included it in HackMD as it includes sensitive information.

The only problem with this method is that we need to know the number of rooms we needed at least 7 weeks before the event.
